### PR TITLE
PostgreSQL Compatibilty

### PR DESCRIPTION
**Pull request by Tilotiti**
I've managed to fix the PostgreSQL compatibilty issues and updated the documentation.

#13

### CODE REVIEW

**Comment by craue** [comment]
While testing with PostgreSQL, I've stumbled upon a few more issues. E.g. I'm getting an [error](https://travis-ci.org/craue/CraueGeoBundle/jobs/216739631#L245) when not adding `->orderBy('poi')`. Can you confirm this behavior?

**Comment by Tilotiti** [comment]
Yep, that's because PostgreSQL, not because of the bundle. With PostgreSQL, you can only GROUP BY on the on the ID. If you want, as MySQL, GROUP BY an other column, you'll have to use the DISTINCT keyword in your SELECT.

That's a weird behavior of PostgreSQL, but when you mention it to the developing team they yeld at you "THAT IS THE STANDARD BITCH". So ...

**Comment by craue** [comment]
How about #15?

**Comment by Tilotiti** [comment]
Peeeeeerfect.

**Pull request closed without merging**
